version : '3'

services:
  nginx:
    container_name:  nginx
    build :
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - bz_static_volume:/BZ/static
      - bz_files_volume:/BZ/files

    networks:
      - nginx_network
volumes:
  bz_static_volume:
    external: true
  bz_files_volume:
    external: true
networks:
  nginx_network:
    external: true